Repository LoFin-official/LoFin-BE, pull requests merged in 2025-06, with the labels that each got.

#33 채팅 기능 구현(실시간 x)
  app.js
  chat/chatHandler.js
  chat/chatServer.js
  config/db.js
  middleware/authMiddleware.js
  routes/coupleprofile.js
  routes/messageRoutes.js
  server.js
Labels: enhancement

#34 [ 📝 Update ] 백엔드 api 수정
  app.js
  chat/chatServer.js
  controllers/coupleCode.js
  controllers/userController.js
  controllers/wishlistUpdateController.js
  crawler/coupangScraper.js
  crawler/recommendGiftByDday.js
  models/User.js
  models/memory.js
  package-lock.json
  package.json
  routes/anniversary.js
  routes/coupleLink.js
  routes/firstMet.js
  routes/memoryRoutes.js
  routes/recommend.js
  routes/wishlist.js
  server.js
Labels: question

#35 Update 추억 백 수정
  app.js
  chat/chatServer.js
  models/memory.js
  routes/memoryRoutes.js
Labels: good first issue
